packages:
  - packages/*
  - examples/*
allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
minimumReleaseAgeExclude:
  - '@testcontainers/clickhouse@12.2.0'
  - hono@4.13.10
  - testcontainers@12.2.0
